version: '3.7'
services:
  php:
    container_name: olena-kupriiets-magento-local.allbugs.info-dev
    image: 'defaultvalue/php:7.4-production'
    user: 'docker:docker'
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: always
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.olena-kupriiets-magento-local-allbugs-info-http.rule=Host(`olena-kupriiets-magento-local.allbugs.info`,`www.olena-kupriiets-magento-local.allbugs.info`,`olena-kupriiets-magento-us.allbugs.info`,`www.olena-kupriiets-magento-us.allbugs.info`)'
      - traefik.http.routers.olena-kupriiets-magento-local-allbugs-info-http.entrypoints=http
      - traefik.http.routers.olena-kupriiets-magento-local-allbugs-info-http.service=olena-kupriiets-magento-local-allbugs-info-http
      - traefik.http.services.olena-kupriiets-magento-local-allbugs-info-http.loadbalancer.server.port=80
      - traefik.http.services.olena-kupriiets-magento-local-allbugs-info-http.loadbalancer.server.scheme=http
      - 'traefik.http.routers.olena-kupriiets-magento-local-allbugs-info-https.rule=Host(`olena-kupriiets-magento-local.allbugs.info`,`www.olena-kupriiets-magento-local.allbugs.info`,`olena-kupriiets-magento-us.allbugs.info`,`www.olena-kupriiets-magento-us.allbugs.info`)'
      - traefik.http.routers.olena-kupriiets-magento-local-allbugs-info-https.entrypoints=https
      - traefik.http.routers.olena-kupriiets-magento-local-allbugs-info-https.tls=true
      - traefik.http.routers.olena-kupriiets-magento-local-allbugs-info-https.service=olena-kupriiets-magento-local-allbugs-info-https
      - traefik.http.services.olena-kupriiets-magento-local-allbugs-info-https.loadbalancer.server.port=443
      - traefik.http.services.olena-kupriiets-magento-local-allbugs-info-https.loadbalancer.server.scheme=https
    extra_hosts:
      - 'olena-kupriiets-magento-local.allbugs.info www.olena-kupriiets-magento-local.allbugs.info olena-kupriiets-magento-us.allbugs.info www.olena-kupriiets-magento-us.allbugs.info:127.0.0.1'
    environment:
      - COMPOSER_VERSION=1
    volumes:
      - '../../:/var/www/html'
      - '${SSL_CERTIFICATES_DIR}:/certs'
      - './apache/virtual-host.conf:/etc/apache2/sites-enabled/000-default.conf:ro'
  mysql:
    image: 'mysql:8.0'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - 'mysql_dev_data:/var/lib/mysql'
      - './mysql/my.cnf:/etc/my.cnf:ro'
  elasticsearch:
    image: 'elasticsearch:7.10.1'
    environment:
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - indices.query.bool.max_clause_count=10240
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - 'elasticsearch_dev_data:/usr/share/elasticsearch/data:rw'
  redis:
    image: 'redis:6.0'
    restart: always
volumes:
  mysql_dev_data:
    external: false
  elasticsearch_dev_data:
    external: false
