<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<h4><?= $escaper->escapeHtml(__('child_block_title')) ?></h4>

<h5><?= $escaper->escapeHtml(__('String')) ?></h5>
<?= $escaper->escapeHtml(__('String parameter: \%1',$block->getData('string_parameter'))) ?>

<h5><?= $escaper->escapeHtml(__('Array')) ?></h5>
<ul>
    <?php foreach($block->getData('array_parameter') as $k => $v): ?>
        <li><?= $escaper->escapeHtml(__('value')) ?>: <?= $v ?>; <?= $escaper->escapeHtml(__('Name')) ?>: <?= $k ?></li>
    <?php endforeach; ?>
</ul>


<h5><?= $escaper->escapeHtml(__('Options')) ?></h5>
<label>
    <select name="test" >
        <?php foreach($block->getData('options_parameter') as $k => $v): ?>
            <option value="<?= $v['value'] ?>"><?= $v['label'] ?></option>
        <?php endforeach; ?>
    </select>
</label>

<h5><?= $escaper->escapeHtml(__('View Model')) ?></h5>
<?= $escaper->escapeHtml(__('ViewModel is instance of: \%1', get_class($block->getData('view_model')))) ?>

<h5><?= $escaper->escapeHtml(__('Helper')) ?></h5>
<?= $escaper->escapeHtml($block->getData('helper_call_result')) ?>
