<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Catalog\Model\Product $product
 */
$product = $block->getData('product');
$isModal = ($block->hasData('is_modal')) ? (int) $block->getData('is_modal') : 0;
// @TODO add customer name and email to the field
?>
<div class="dv-campus-personal-discount-request">
    <form class="form olenak-personal-discount-form"
          action="/errors/404.php"
          onsubmit="return false;"
          method="post"
          data-mage-init='{"OlenaK_RegularCustomer_form": {
                                  "action": "<?= $escaper->escapeHtmlAttr($block->getData('request_submit_url')) ?>",
                                  "actionCheck": "<?= $escaper->escapeHtmlAttr($block->getData('request_check_url')) ?>",
                                  "isModal": <?= $escaper->escapeHtmlAttr($isModal) ?>
                            }
          }'

    >
        <fieldset class="fieldset">
            <div class="field name required">
                <label class="label" for="name">
                    <span><?= $escaper->escapeHtml(__('Your name')) ?></span>
                </label>
                <div class="control">
                    <input name="name"
                           title="<?= $escaper->escapeHtmlAttr(__('Your name')) ?>"
                           class="input-text"
                           type="text"
                           data-validate="{required:true}"
                    />
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email">
                    <span><?= $escaper->escapeHtml(__('Your email')) ?></span>
                </label>
                <div class="control">
                    <input name="email"
                           title="<?= $escaper->escapeHtmlAttr(__('Your email')) ?>"
                           class="input-text"
                           type="email"
                           data-validate="{required:true, 'validate-email':true}"
                    />
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden"
                       name="product_id"
                       value="<?= ($product) ? $escaper->escapeHtmlAttr((int) $product->getId()) : '' ?>"
                />
                <input type="hidden"
                       name="product_name"
                       value="<?= ($product) ? $escaper->escapeHtmlAttr((string) $product->getName()) : '' ?>"
                />
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Send your request')) ?>"
                        class="action submit primary"
                >
                    <span><?= $escaper->escapeHtml(__('Send your request')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
